### ISSUE TITLE
speedlimit doesnt really do anything

### ISSUE THREAD

**Issue by willcannotpaythebills** [gcurtiss/protocol3#31]
im flying at a constant~ 48.3 bps and this happens. 

how to reproduce: 
fly in a straight line above height limit so u dont run into smth
fly at a steady rate 
![image](https://user-images.githubusercontent.com/77316348/111854500-cc7f2780-88dc-11eb-805e-e783b82fea31.png)

**Comment by gcurtiss** [comment]
that's because your speed dips to below 48 because of natural tps fluctuation so the timer starts counting backwards (when you're going above speed limit, timer counts down from 10 to 0, when you start going normally, it resets your timer from 0 to 10). since the dips happen at random and small rates, your timer resets very quickly (from 9s left to 10s left). this wont reproduce if you fly at a rate like 50+ bps, but ~0.1 to ~1.0 is negligble and im not really concerned about restricting the speed limit to cater to that
